name: Lint

on: 
  workflow_dispatch:
    paths:
      - 'src/**'

jobs:
  lint_with_luacheck:
    runs_on: ubuntu_latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install lua
        uses: leafo/gh-actions-lua@v8
      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Lint with luacheck
        run: |
          luarocks install luacheck
          make lint-lua
